data:
  batch_size: 32
  num_workers: 0
  pin_mem: False

  # CSI .pt 根目录（preprocess_to_pt.py 的 DST_DIR）
  root_path: /root/autodl-tmp/csi_preprocessed/

  # CSI tensor settings
  crop_size: 128
  in_chans: 16
  noise_sigma: 0.0

  # 可选：如果你提前统计了 16 通道 mean/std，就填这里；否则留空用“每样本标准化”
  normalization: null
  # normalization:
  #   mean: [ ... 16 numbers ... ]
  #   std:  [ ... 16 numbers ... ]
logging:
  folder: /root/autodl-tmp/ijepa_runs/vith14_224_ep300_scaled/
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio: [0.75, 1.5]
  enc_mask_scale: [0.85, 1.0]
  pred_mask_scale: [0.15, 0.2]
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4

  # 关键：patch_size 必须整除 crop_size (128)
  patch_size: 4
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
